getting there

diff --git a/container b/container
--- a/container
+++ b/container
@@ -1,18 +1,28 @@
 #!/bin/bash
 
+#### USAGE
+#
+#   * Dockerfile should run: containter setup-container
+#   * devcontainer.json should run: containter setup-project (in postCreateCommand)
+#   * vscode tasks should
+#
+
 set -e
 
 plugins=
+user_root=0
+user_vscode=1000
 
-if [[ -f "$ENV_FILE" ]]; then
-    source "$ENV_FILE"
-fi
+[ -n "$DEVIMAGE_DIR" ] || die "DEVIMAGE_DIR not set (set in Dockerfile)"
+HA_DEFAULT_CONF_INSTALL=$DEVIMAGE_DIR/homeassistant_default_config
+
+
 
 function info(){
     local YELLOW='\033[1;33m'
     local NC='\033[0m' # No Color
     echo -e "${YELLOW}$1${NC}"
-} 
+}
 
 function errEcho() {
     local RED='\033[0;31m'
@@ -23,8 +33,13 @@ function die() {
     errEcho "$1" && exit 1 
 }
 
-[ -n "$HA_DIR" ] || die "HA_DIR not set"
-[ -n "$HA_CONFIG_DIR" ] || die "HA_CONFIG_DIR not set"
+function requireUser() {
+ 
+    if [ "$(id -u)" != "$1" ]; then
+        die "Please run as ${1}, not as $(id -u)"
+        exit 1
+    fi
+}
 
 function create_hass_user() {
     local username=${HASS_USERNAME:-dev}
@@ -34,6 +49,7 @@ function create_hass_user() {
 }
 
 function bypass_onboarding() {
+
     cat > ${HA_CONFIG_DIR}/.storage/onboarding << EOF
 {
     "data": {
@@ -49,8 +65,41 @@ function bypass_onboarding() {
 EOF
 }
 
+function install_custom_components() {
+
+    # on the form "Kaptensanders/skolmat" ->   https://github.com/Kaptensanders/skolmat/trunk/custom_components
+
+    if [ -z "$HA_CUSTOM_COMPONENTS" ]; then
+        info "No custom components to setup"
+        return
+    else
+        info "Setting up custom components: $HA_CUSTOM_COMPONENTS"
+    fi
+
+    mkdir -p $HA_CONFIG_DIR/custom_components
+
+    TMPDIR=/tmp/ha_custom_components
+    sudo rm -Rf $TMPDIR
+    mkdir $TMPDIR/
+
+    cd $TMPDIR
+    for component in $HA_CUSTOM_COMPONENTS
+    do
+        snv export "https://github.com/${component}/trunk/custom_components"
+        mv ./custom_components/* $HA_CONFIG_DIR/custom_components/
+        rm -Rf ./custom_components
+    done
+
+    cd ..
+    rm -Rf $TMPDIR
+
+} 
+
 function fetch_lovelace_plugins() {
-    for plugin in $LOVELACE_PLUGINS
+
+    # from @thomasloven
+
+    for plugin in $HA_LOVELACE_PLUGINS
     do
         local author=$(cut -d '/' -f1 <<<"$plugin")
         local repo=$(cut -d '/' -f2 <<<"$plugin")
@@ -74,6 +123,8 @@ function fetch_lovelace_plugins() {
 
 function install_lovelace_plugins() {
 
+    # from @thomasloven
+
     for file in $LOVELACE_LOCAL_FILES
     do
         plugins="${plugins} /local/workspace/${file}"
@@ -83,6 +134,7 @@ function install_lovelace_plugins() {
 
     if [ -z "$plugins" ]; then
         info "No Lovelace plugins to setup"
+        return
     else
         info "Setting up Lovelace plugins: $plugins"
     fi
@@ -123,30 +175,9 @@ EOF
 EOF
 }
 
-function install_hacs() {
-    cd ${HA_CONFIG_DIR}
-    curl -sfSL https://get.hacs.xyz | bash -
-}
+function setup_environment() {
 
-function setup_hass_config() {
-
-    mkdir -p ${HA_CONFIG_DIR}/custom_components
-    mkdir -p ${HA_CONFIG_DIR}/www  
-
-    echo "$(hass --version)" > ${HA_CONFIG_DIR}/.HA_VERSION
-    hass -c $HA_CONFIG_DIR --script ensure_config
-}
-
-function install_custom_components(){
-    errEcho "ERROR: Custom components setup not implemented!"
-    if [ "$CUSTOM_COMPONENTS" != "" ]; then 
-        errEcho "Install the following manually ${CUSTOM_COMPONENTS}"
-    fi
-}
-
-function fix_env() {
-
-    cat << EOF > /home/vscode/.bash_aliases
+    cat << 'EOF' > /home/vscode/.bash_aliases
 alias grep='grep --color=auto'
 alias fgrep='fgrep --color=auto'
 alias egrep='egrep --color=auto'
@@ -155,36 +186,35 @@ alias la='ls -la'
 alias l='ls -CF'
 alias ..='cd ..'
 alias p='python3'
-alias ha='sudo hass -c ${HA_CONFIG_DIR} -v'
-alias halog='tail -f ${HA_CONFIG_DIR}/homeassistant.log'
+alias ha='container hass-run'
+alias ha-debug='container hass-debug'
+alias halog='tail -n 200 -f ${HA_CONFIG_DIR}/home-assistant.log'
 EOF
-    sudo chown vscode:vscode /home/vscode/.bash_aliases
-    cat << EOF >> /home/vscode/.bashrc
 
+
+echo "export HA_CONFIG_DIR=\${HA_CONFIG_DIR:-\"$HA_DEFAULT_CONF_INSTALL\"}" >> /home/vscode/.bashrc
+echo "export WORKSPACE_DIR=\${WORKSPACE_DIR:-\"/home/vscode\"}" >> /home/vscode/.bashrc
+
+    cat << 'EOF' >> /home/vscode/.bashrc
+export PYTHONPATH="${PYTHONPATH}:${WORKSPACE_DIR}/custom_components"
+cd $WORKSPACE_DIR
 echo "Devcontainer running:"
 echo "* $(python --version)"
 echo "* Home Assistant $(cat ${HA_CONFIG_DIR}/.HA_VERSION)" 
+echo "* Run 'ha' to start Home Assistant"
 EOF
+ 
     git config --global alias.co checkout
     git config --global alias.br branch
     git config --global alias.ci commit
     git config --global alias.st status
 }
 
-function install_ha() {
-
-    info "Installing $HA_VERSION in $HA_DIR..."
-
-    git clone --branch $HA_VERSION --single-branch --depth 1 https://github.com/home-assistant/core.git ${HA_DIR}
-    git config --global --add safe.directory ${HA_DIR}
-    pip install --upgrade -e ${HA_DIR}
-}
-
 function init_ha() {
 
     # HA seems to have issues on first run to install modules, maybe a race condition issue with pip. Works better second time
 
-    info "Initializing Home Assistant..."
+    info "Initializing Home Assistant in $HA_CONFIG_DIR"
     local retries="${1:-1}"
     local success=1
 
@@ -200,9 +230,13 @@ function init_ha() {
             echo "$line"
             if [[ "$line" == *"[homeassistant.setup] Setup failed for"*  ]]; then
                 success=0
-                kill -INT "$COPROC_PID"
-                errEcho "Detected a problem in Homeassistant initialization, aborting..."
-                sleep 4
+                echo "$COPROC_PID Fail"
+                
+                if [ -n "$COPROC_PID" ]; then # check for pid var first to avoid race condition
+                    echo "Kiling $COPROC_PID"
+                    kill -INT "$COPROC_PID"
+                    wait "$COPROC_PID" || true
+                fi
             fi
 
             if [[ "$line" == *"Starting Home Assistant"* ]]; then
@@ -213,72 +247,133 @@ function init_ha() {
 
         if [ "$success" -eq "1" ]; then
             info "Home Assistant initialization done"
-            break            
+            break
+        else
+            errEcho "Detected a problem in Homeassistant initialization, aborting..."
         fi
 
     done
     
     [ "$success" -eq "1" ] || die "Failed to initialize Home assistant"
-
 }
 
-function setup() {
+function setup_ha() {
 
-    install_ha
-    setup_hass_config
+    # homeassistant is already installed by Dockerfile
+    
+    # perform a default installation in HA_DEFAULT_CONF_INSTALL
+    # used to fast track project ha config setup
+
+    info "Installing default HA configuration in $HA_DEFAULT_CONF_INSTALL"
+
+    hass --script ensure_config -c $HA_DEFAULT_CONF_INSTALL
+    mkdir -p $HA_DEFAULT_CONF_INSTALL
+    HA_CONFIG_DIR=$HA_DEFAULT_CONF_INSTALL init_ha 3
+}
+
+function setup_hass_config_dir() {
+
+    info "Setting up hass config dir in $HA_CONFIG_DIR"
+    sudo rm -Rf $HA_CONFIG_DIR
+
+    mkdir -p $HA_CONFIG_DIR/custom_components
+    mkdir -p $HA_CONFIG_DIR/www
+    mkdir -p $HA_CONFIG_DIR/.storage
+
+    # Dockerfile should copy ha_configuration.yaml to DEVIMAGE_DIR
+    cp ${DEVIMAGE_DIR}/ha_configuration_base.yaml $HA_CONFIG_DIR/configuration.yaml
+
+    # import contents of .devcontainer/ha_config/ to config dir
+    # *.append files are appended to existing files, other files are soft linked
+    cd $WORKSPACE_DIR/.devcontainer/ha_config
+    for file in *
+    do
+        target=$HA_CONFIG_DIR/$(basename -s .append $file)
+        if [[ $file == *.append ]]; then
+            # append to existing
+            echo "appending: $file to $target"
+            cat $file >> $target
+        else
+            # link file
+            echo "Creating link $target"
+            ln -s $PWD/$file $target
+        fi
+        
+    done
+
+    # move the deps folder of the default installation to this config to make it easier to setup hass first time
+    info "Bootstrapping $HA_CONFIG_DIR with dependencies from default config installation" 
+    mv $HA_DEFAULT_CONF_INSTALL/deps $HA_CONFIG_DIR
+
+    hass --script ensure_config -c $HA_CONFIG_DIR
+    echo "$(hass --version)" > $HA_CONFIG_DIR/.HA_VERSION
+}
+
+# run from Dockerfile
+function setup_container() {
+
+    requireUser $user_vscode
+
+    [ -n "$HA_VERSION" ] || die "HA_VERSION not set"
+
+    setup_ha
+    setup_environment
+}
+
+# run from devcontainer.json postCreateCommand
+# devcontainer.json should set HA_CONFIG_DIR (preferably in ./devcontainer container.env file as --env-file argument to docker run)
+function setup_project() {
+    
+    requireUser $user_vscode
+
+    [ -n "$HA_VERSION" ]    || die "HA_VERSION not set"
+    [ -n "$WORKSPACE_DIR" ] || die "WORKSPACE_DIR not set, should be the repository folder"
+    [ -n "$HA_CONFIG_DIR" ] || die "HA_CONFIG_DIR not set, should typically be WORKSPACE_DIR/ha_config"
+
+    setup_hass_config_dir
     create_hass_user
     bypass_onboarding
-    install_hacs
-    install_lovelace_plugins
-    init_ha 2
-    fix_env
 
-    info "Setting file permissions..."
-    cd /workspace
-    chown -R vscode:vscode .
-
-    info "\n** Home Assistant $(hass --version) is ready to use **\n"
-
-}
-
-
-# run from client project container to setup extra directives, typically /workspace/.devcontainer/setup.env is sourced
-function setup_project(){
     install_custom_components
     install_lovelace_plugins
 
-    # merge conf files
-    if test -f ${HA_CONFIG_DIR}/append_ha_config.yaml; then
-        cat ${HA_CONFIG_DIR}/append_ha_config.yaml >> ${HA_CONFIG_DIR}/configuration.yaml
-    fi
+    info "\nPlease logout and login again to complete setup process\n"
 
-    init_ha
+    info "To open a devcontainer and load a .code-workspace directly from command line, see this script:"
+    info "https://gist.github.com/Kaptensanders/79da7c1547751fb43c75904e3110bbf9\n"
 
-    info "Setting file permissions..."
-    cd $HA_CONFIG_DIR
-    chown -R vscode:vscode .
 }
 
-function run() {
-    hass -c ${HA_CONFIG_DIR} -v
+function hass_run() {
+    
+    requireUser $user_vscode
+    # must start from the WORKSPACE_DIR or the PYTHON_PATH wont have any effect (for some reason)
+    cd $WORKSPACE_DIR
+    hass -v -c $HA_CONFIG_DIR
 }
 
+function hass_debug() {
 
+    requireUser $user_vscode
+    # must start from the WORKSPACE_DIR or the PYTHON_PATH wont have any effect (for some reason)
+    cd $WORKSPACE_DIR
+    hass -v -c $HA_CONFIG_DIR --debug
+}
 
 case $1 in
-    setup)
-        setup
-        ;;
-    init-hass)
-        init_hass
-        ;;
-    run-hass)
-        run
+    setup-container)
+        setup_container
         ;;
     setup-project)
         setup_project
         ;;
+    hass-run)
+        hass_run
+        ;;
+    hass-debug)
+        hass_debug
+        ;;
     *)
-        info "Use with setup, init-hass or run-hass"
+        info "Usage: setup_container or setup_project"
         ;;
 esac
