misc

diff --git a/container b/container
--- a/container
+++ b/container
@@ -4,19 +4,37 @@ set -e
 
 plugins=
 
-function ensure_hass_config() {
-    hass --script ensure_config -c /config
+if [[ -f "$ENV_FILE" ]]; then
+    source "$ENV_FILE"
+fi
+
+function info(){
+    local YELLOW='\033[1;33m'
+    local NC='\033[0m' # No Color
+    echo -e "${YELLOW}$1${NC}"
+} 
+
+function errEcho() {
+    local RED='\033[0;31m'
+    local NC='\033[0m' # No Color
+    echo -e "${RED}$1${NC}" 1>&2
 }
+function die() {
+    errEcho "$1" && exit 1 
+}
+
+[ -n "$HA_DIR" ] || die "HA_DIR not set"
+[ -n "$HA_CONFIG_DIR" ] || die "HA_CONFIG_DIR not set"
 
 function create_hass_user() {
     local username=${HASS_USERNAME:-dev}
     local password=${HASS_PASSWORD:-dev}
-    echo "Creating Home Assistant User ${username}:${password}"
-    hass --script auth -c /config add ${username} ${password}
+    info "Creating Home Assistant User ${username}:${password}"
+    hass --script auth -c ${HA_CONFIG_DIR} add ${username} ${password}
 }
 
 function bypass_onboarding() {
-    cat > /config/.storage/onboarding << EOF
+    cat > ${HA_CONFIG_DIR}/.storage/onboarding << EOF
 {
     "data": {
         "done": [
@@ -32,7 +50,6 @@ EOF
 }
 
 function fetch_lovelace_plugins() {
-    mkdir -p /config/www/workspace
     for plugin in $LOVELACE_PLUGINS
     do
         local author=$(cut -d '/' -f1 <<<"$plugin")
@@ -46,16 +63,17 @@ function fetch_lovelace_plugins() {
             file=$repo
         fi
 
-        echo "Downloading ${plugin} to ${file}.js"
-        curl https://raw.githubusercontent.com/${author}/${repo}/master/dist/${file}.js --output /config/www/${file}.js --fail \
-        || curl https://raw.githubusercontent.com/${author}/${repo}/master/${file}.js --output /config/www/${file}.js --fail \
-        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}.js --output /config/www/${file}.js --fail \
-        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}-bundle.js --output /config/www/${file}.js --fail
+        info "Downloading ${plugin} to ${file}.js"
+        curl https://raw.githubusercontent.com/${author}/${repo}/master/dist/${file}.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail \
+        || curl https://raw.githubusercontent.com/${author}/${repo}/master/${file}.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail \
+        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail \
+        || curl -L https://github.com/${author}/${repo}/releases/latest/download/${file}-bundle.js --output ${HA_CONFIG_DIR}/www/${file}.js --fail
         plugins="${plugins} /local/${file}.js"
     done
 }
 
 function install_lovelace_plugins() {
+
     for file in $LOVELACE_LOCAL_FILES
     do
         plugins="${plugins} /local/workspace/${file}"
@@ -63,7 +81,15 @@ function install_lovelace_plugins() {
 
     fetch_lovelace_plugins
 
-    cat > /config/.storage/lovelace_resources << EOF
+    if [ -z "$plugins" ]; then
+        info "No Lovelace plugins to setup"
+    else
+        info "Setting up Lovelace plugins: $plugins"
+    fi
+
+
+
+    cat > ${HA_CONFIG_DIR}/.storage/lovelace_resources << EOF
 {
     "data": {
         "items": [
@@ -73,12 +99,12 @@ EOF
     for plugin in $plugins
     do
         if [ $i -gt "0" ]; then
-            echo "," >> /config/.storage/lovelace_resources
+            echo "," >> ${HA_CONFIG_DIR}/.storage/lovelace_resources
         fi
 
         i=$((i+1))
 
-        head -c -1 >> /config/.storage/lovelace_resources << EOF
+        head -c -1 >> ${HA_CONFIG_DIR}/.storage/lovelace_resources << EOF
             {
                 "id": "${i}",
                 "type": "module",
@@ -87,7 +113,7 @@ EOF
 EOF
     done
 
-    cat >> /config/.storage/lovelace_resources << EOF
+    cat >> ${HA_CONFIG_DIR}/.storage/lovelace_resources << EOF
 
         ]
     },
@@ -98,29 +124,24 @@ EOF
 }
 
 function install_hacs() {
-    cd /config
+    cd ${HA_CONFIG_DIR}
     curl -sfSL https://get.hacs.xyz | bash -
-}
-
-function install_ha_dev() {
-
-    local VERSION=${HA_VERSION:-dev}
-    echo "Installing Home Assistant $VERSION in /usr/src/homeassistant"
-
-    rm -rf /usr/src/homeassistant
-    git clone --branch $VERSION --single-branch --depth 1 https://github.com/home-assistant/core.git /usr/src/homeassistant
-    git config --global --add safe.directory /usr/src/homeassistant
-
-    pip install --upgrade -e /usr/src/homeassistant
-        
-    echo "$(hass --version)" > /config/.HA_VERSION
 }
 
 function setup_hass_config() {
 
-    mkdir -p /config/custom_components
-    mkdir -p /config/www
+    mkdir -p ${HA_CONFIG_DIR}/custom_components
+    mkdir -p ${HA_CONFIG_DIR}/www  
 
+    echo "$(hass --version)" > ${HA_CONFIG_DIR}/.HA_VERSION
+    hass -c $HA_CONFIG_DIR --script ensure_config
+}
+
+function install_custom_components(){
+    errEcho "ERROR: Custom components setup not implemented!"
+    if [ "$CUSTOM_COMPONENTS" != "" ]; then 
+        errEcho "Install the following manually ${CUSTOM_COMPONENTS}"
+    fi
 }
 
 function fix_env() {
@@ -134,17 +155,15 @@ alias la='ls -la'
 alias l='ls -CF'
 alias ..='cd ..'
 alias p='python3'
-alias ha='sudo hass -c /config -v'
-alias halog='tail -f /config/homeassistant.log'
+alias ha='sudo hass -c ${HA_CONFIG_DIR} -v'
+alias halog='tail -f ${HA_CONFIG_DIR}/homeassistant.log'
 EOF
-   
     sudo chown vscode:vscode /home/vscode/.bash_aliases
-
     cat << EOF >> /home/vscode/.bashrc
 
 echo "Devcontainer running:"
 echo "* $(python --version)"
-echo "* Home Assistant $(hass --version)" 
+echo "* Home Assistant $(cat ${HA_CONFIG_DIR}/.HA_VERSION)" 
 EOF
     git config --global alias.co checkout
     git config --global alias.br branch
@@ -152,24 +171,76 @@ EOF
     git config --global alias.st status
 }
 
-# executed to 
+function install_ha() {
+
+    info "Installing $HA_VERSION in $HA_DIR..."
+
+    git clone --branch $HA_VERSION --single-branch --depth 1 https://github.com/home-assistant/core.git ${HA_DIR}
+    git config --global --add safe.directory ${HA_DIR}
+    pip install --upgrade -e ${HA_DIR}
+}
+
+function init_ha() {
+
+    # HA seems to have issues on first run to install modules, maybe a race condition issue with pip. Works better second time
+
+    info "Initializing Home Assistant..."
+    local retries="${1:-1}"
+    local success=1
+
+    for (( i=0; i<$retries; i++ ))
+    do
+        if [ "$success" -ne "1" ]; then
+            info "\nRetrying HA init...\n"
+        fi
+
+        success=1
+        coproc (hass -c ${HA_CONFIG_DIR} -v 2>&1;)
+        while IFS= read -r line; do
+            echo "$line"
+            if [[ "$line" == *"[homeassistant.setup] Setup failed for"*  ]]; then
+                success=0
+                kill -INT "$COPROC_PID"
+                errEcho "Detected a problem in Homeassistant initialization, aborting..."
+                sleep 4
+            fi
+
+            if [[ "$line" == *"Starting Home Assistant"* ]]; then
+                sleep 3
+                kill -INT "$COPROC_PID"
+            fi
+        done <&"${COPROC[0]}"
+
+        if [ "$success" -eq "1" ]; then
+            info "Home Assistant initialization done"
+            break            
+        fi
+
+    done
+    
+    [ "$success" -eq "1" ] || die "Failed to initialize Home assistant"
+
+}
+
 function setup() {
-    install_ha_dev
+
+    install_ha
     setup_hass_config
-    ensure_hass_config
     create_hass_user
     bypass_onboarding
     install_hacs
     install_lovelace_plugins
+    init_ha 2
     fix_env
+
+    info "Setting file permissions..."
+    cd /workspace
+    chown -R vscode:vscode .
+
+    info "\n** Home Assistant $(hass --version) is ready to use **\n"
+
 }
 
-function install_custom_components(){
-    >&2 echo "ERROR: Custom components setup not implemented!"
-    if [ "$CUSTOM_COMPONENTS" != "" ]; then 
-        >&2 echo "Install the following manually ${CUSTOM_COMPONENTS}"
-    fi
-}
 
 # run from client project container to setup extra directives, typically /workspace/.devcontainer/setup.env is sourced
 function setup_project(){
@@ -177,35 +248,22 @@ function setup_project(){
     install_lovelace_plugins
 
     # merge conf files
-    if test -f /config/append_ha_config.yaml; then
-        cat /config/append_ha_config.yaml >> /config/configuration.yaml
+    if test -f ${HA_CONFIG_DIR}/append_ha_config.yaml; then
+        cat ${HA_CONFIG_DIR}/append_ha_config.yaml >> ${HA_CONFIG_DIR}/configuration.yaml
     fi
 
-    init_hass
+    init_ha
+
+    info "Setting file permissions..."
+    cd $HA_CONFIG_DIR
+    chown -R vscode:vscode .
 }
 
 function run() {
-    hass -c /config -v
+    hass -c ${HA_CONFIG_DIR} -v
 }
 
-function init_hass(){
 
-    echo "Initializing Home Assistant..."
-
-    coproc (hass -c /config -v 2>&1;)
-    while IFS= read -r line; do
-        echo "$line"
-        if [[ "$line" == *"Starting Home Assistant"* ]]; then
-            echo "Home Assistant initialization done"
-            sleep 5
-            kill -INT "$COPROC_PID"
-        fi
-    done <&"${COPROC[0]}"
-}
-
-if [[ -f "$ENV_FILE" ]]; then
-    source "$ENV_FILE"
-fi
 
 case $1 in
     setup)
@@ -214,13 +272,13 @@ case $1 in
     init-hass)
         init_hass
         ;;
-    launch-hass)
+    run-hass)
         run
         ;;
     setup-project)
         setup_project
         ;;
     *)
-        echo "Use with setup or launch-hass"
+        info "Use with setup, init-hass or run-hass"
         ;;
 esac
